import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsString,
  IsNotEmpty,
  IsOptional,
  IsEnum,
  MaxLength,
  IsArray,
  IsUrl,
  IsNumber,
  Min,
  IsBoolean,
} from 'class-validator';

export enum RegionType {
  US = 'us',
  ES = 'es',
}

export enum LanguageType {
  EN = 'en',
  ES = 'es',
}

export class SendMessageDto {
  @ApiProperty({
    description: 'The user message to send to the chatbot',
    example: 'What courses are available in the academy?',
  })
  @IsString()
  @IsNotEmpty()
  @MaxLength(2000)
  message: string;

  @ApiPropertyOptional({
    description: 'Conversation ID for continuing an existing chat',
    example: '507f1f77bcf86cd799439011',
  })
  @IsString()
  @IsOptional()
  conversationId?: string;

  @ApiPropertyOptional({
    description: 'Guest session ID for anonymous users (generated by frontend)',
    example: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  })
  @IsString()
  @IsOptional()
  guestId?: string;

  @ApiPropertyOptional({
    description: 'User region for region-specific content',
    enum: RegionType,
    default: RegionType.ES,
  })
  @IsEnum(RegionType)
  @IsOptional()
  region?: RegionType;

  @ApiPropertyOptional({
    description: 'User preferred language',
    enum: LanguageType,
    default: LanguageType.ES,
  })
  @IsEnum(LanguageType)
  @IsOptional()
  language?: LanguageType;
}

export class QuickSuggestionDto {
  @ApiProperty({ description: 'Suggestion label' })
  label: string;

  @ApiProperty({ description: 'Suggestion message to send' })
  message: string;

  @ApiPropertyOptional({ description: 'Category of suggestion' })
  category?: string;
}

export class ChatHistoryQueryDto {
  @ApiPropertyOptional({ description: 'Page number', default: 1 })
  @IsOptional()
  page?: number;

  @ApiPropertyOptional({ description: 'Items per page', default: 20 })
  @IsOptional()
  limit?: number;
}

export class CreateKnowledgeDocumentDto {
  @ApiProperty({
    description: 'Region this document applies to',
    enum: ['us', 'es', 'both'],
  })
  @IsString()
  @IsNotEmpty()
  region: string;

  @ApiProperty({
    description: 'Category of the document',
    enum: ['faq', 'academy', 'mentorship', 'navigation', 'pricing', 'general'],
  })
  @IsString()
  @IsNotEmpty()
  category: string;

  @ApiProperty({ description: 'Document title' })
  @IsString()
  @IsNotEmpty()
  title: string;

  @ApiProperty({ description: 'Document content' })
  @IsString()
  @IsNotEmpty()
  content: string;

  @ApiProperty({
    description: 'Language of the document',
    enum: ['en', 'es'],
  })
  @IsString()
  @IsNotEmpty()
  language: string;

  @ApiPropertyOptional({ description: 'Tags for categorization', type: [String] })
  @IsArray()
  @IsString({ each: true })
  @IsOptional()
  tags?: string[];

  @ApiPropertyOptional({ description: 'Whether the document is active', default: true })
  @IsBoolean()
  @IsOptional()
  isActive?: boolean;
}

export class UpdateKnowledgeDocumentDto {
  @ApiPropertyOptional({ description: 'Document title' })
  @IsString()
  @IsOptional()
  title?: string;

  @ApiPropertyOptional({ description: 'Document content' })
  @IsString()
  @IsOptional()
  content?: string;

  @ApiPropertyOptional({
    description: 'Region this document applies to',
    enum: ['us', 'es', 'both'],
  })
  @IsString()
  @IsOptional()
  region?: string;

  @ApiPropertyOptional({
    description: 'Category of the document',
    enum: ['faq', 'academy', 'mentorship', 'navigation', 'pricing', 'general'],
  })
  @IsString()
  @IsOptional()
  category?: string;

  @ApiPropertyOptional({
    description: 'Language of the document',
    enum: ['en', 'es'],
  })
  @IsString()
  @IsOptional()
  language?: string;

  @ApiPropertyOptional({ description: 'Tags for categorization', type: [String] })
  @IsArray()
  @IsString({ each: true })
  @IsOptional()
  tags?: string[];

  @ApiPropertyOptional({ description: 'Whether document is active' })
  @IsBoolean()
  @IsOptional()
  isActive?: boolean;
}

export enum KnowledgeCategoryType {
  FAQ = 'faq',
  ACADEMY = 'academy',
  MENTORSHIP = 'mentorship',
  NAVIGATION = 'navigation',
  PRICING = 'pricing',
  GENERAL = 'general',
}

export class UploadPdfDto {
  @ApiProperty({
    description: 'Category of the document',
    enum: KnowledgeCategoryType,
  })
  @IsEnum(KnowledgeCategoryType)
  @IsNotEmpty()
  category: KnowledgeCategoryType;

  @ApiProperty({
    description: 'Language of the document',
    enum: LanguageType,
  })
  @IsEnum(LanguageType)
  @IsNotEmpty()
  language: LanguageType;

  @ApiPropertyOptional({
    description: 'Custom title for the document (auto-extracted from PDF if not provided)',
  })
  @IsString()
  @IsOptional()
  title?: string;

  @ApiPropertyOptional({
    description: 'Tags for categorization',
    type: [String],
  })
  @IsArray()
  @IsString({ each: true })
  @IsOptional()
  tags?: string[];
}

export class AddUrlDocumentDto {
  @ApiProperty({
    description: 'URL to extract content from',
    example: 'https://daytradefak.com/community-event',
  })
  @IsUrl()
  @IsNotEmpty()
  url: string;

  @ApiProperty({
    description: 'Category of the document',
    enum: KnowledgeCategoryType,
  })
  @IsEnum(KnowledgeCategoryType)
  @IsNotEmpty()
  category: KnowledgeCategoryType;

  @ApiProperty({
    description: 'Language of the document',
    enum: LanguageType,
  })
  @IsEnum(LanguageType)
  @IsNotEmpty()
  language: LanguageType;

  @ApiPropertyOptional({
    description: 'Custom title (auto-extracted from page if not provided)',
  })
  @IsString()
  @IsOptional()
  title?: string;

  @ApiPropertyOptional({
    description: 'Tags for categorization',
    type: [String],
  })
  @IsArray()
  @IsString({ each: true })
  @IsOptional()
  tags?: string[];

  @ApiPropertyOptional({
    description: 'Auto-refresh interval in hours (null = no auto-refresh)',
    example: 24,
  })
  @IsNumber()
  @Min(1)
  @IsOptional()
  refreshIntervalHours?: number;
}

export class UpdateUrlSourceDto {
  @ApiPropertyOptional({ description: 'Custom title' })
  @IsString()
  @IsOptional()
  title?: string;

  @ApiPropertyOptional({
    description: 'Category of the document',
    enum: KnowledgeCategoryType,
  })
  @IsEnum(KnowledgeCategoryType)
  @IsOptional()
  category?: KnowledgeCategoryType;

  @ApiPropertyOptional({
    description: 'Language of the document',
    enum: LanguageType,
  })
  @IsEnum(LanguageType)
  @IsOptional()
  language?: LanguageType;

  @ApiPropertyOptional({
    description: 'Tags for categorization',
    type: [String],
  })
  @IsArray()
  @IsString({ each: true })
  @IsOptional()
  tags?: string[];

  @ApiPropertyOptional({
    description: 'Auto-refresh interval in hours (null = disable auto-refresh)',
  })
  @IsNumber()
  @Min(1)
  @IsOptional()
  refreshIntervalHours?: number | null;

  @ApiPropertyOptional({ description: 'Whether URL source is active' })
  @IsBoolean()
  @IsOptional()
  isActive?: boolean;
}
