export enum TradeType {
  CALL = 'call',
  PUT = 'put',
}

export enum Role {
  USER = 'user',
  ADMIN = 'admin',
}

export enum VariableKeys {
  AWS_ClASS_FOLDER = 'AWS_S3_CLASS_VIDEO_FOLDER',
  AWS_MENTORSHIP_FOLDER = 'AWS_S3_MENTORSHIP_FOLDER',
  AWS_S3_STOCK_VIDEO_FOLDER = 'AWS_S3_STOCK_VIDEO_FOLDER',
  AWS_S3_PSICOTRADING_VIDEO_FOLDER = 'AWS_S3_PSICOTRADING_VIDEO_FOLDER',
  AWS_S3_CURSO_1_FOLDER = 'AWS_S3_CURSO_1_FOLDER',
}
